FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY backend/Home4Paws.API.csproj .
RUN dotnet restore Home4Paws.API.csproj
COPY backend/ .
RUN dotnet build Home4Paws.API.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish Home4Paws.API.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Home4Paws.API.dll"]
